// <auto-generated />
using System;
using ClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataClassLibary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503061803_ValidationOnModel")]
    partial class ValidationOnModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.SerialNumberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 0,
                            SerialNumber = "ACME-001-NH35"
                        },
                        new
                        {
                            Id = 2,
                            Count = 0,
                            SerialNumber = "ACME-002-C17T"
                        },
                        new
                        {
                            Id = 3,
                            Count = 0,
                            SerialNumber = "ACME-003-PNDQ"
                        },
                        new
                        {
                            Id = 4,
                            Count = 0,
                            SerialNumber = "ACME-004-QBRA"
                        },
                        new
                        {
                            Id = 5,
                            Count = 0,
                            SerialNumber = "ACME-005-XWWT"
                        },
                        new
                        {
                            Id = 6,
                            Count = 0,
                            SerialNumber = "ACME-006-WFH0"
                        },
                        new
                        {
                            Id = 7,
                            Count = 0,
                            SerialNumber = "ACME-007-3GH0"
                        },
                        new
                        {
                            Id = 8,
                            Count = 0,
                            SerialNumber = "ACME-008-V535"
                        },
                        new
                        {
                            Id = 9,
                            Count = 0,
                            SerialNumber = "ACME-009-JHWC"
                        },
                        new
                        {
                            Id = 10,
                            Count = 0,
                            SerialNumber = "ACME-010-TXF1"
                        },
                        new
                        {
                            Id = 11,
                            Count = 0,
                            SerialNumber = "ACME-011-86XB"
                        },
                        new
                        {
                            Id = 12,
                            Count = 0,
                            SerialNumber = "ACME-012-EHKV"
                        },
                        new
                        {
                            Id = 13,
                            Count = 0,
                            SerialNumber = "ACME-013-TUUN"
                        },
                        new
                        {
                            Id = 14,
                            Count = 0,
                            SerialNumber = "ACME-014-YX78"
                        },
                        new
                        {
                            Id = 15,
                            Count = 0,
                            SerialNumber = "ACME-015-71ML"
                        },
                        new
                        {
                            Id = 16,
                            Count = 0,
                            SerialNumber = "ACME-016-56S1"
                        },
                        new
                        {
                            Id = 17,
                            Count = 0,
                            SerialNumber = "ACME-017-KQ3F"
                        },
                        new
                        {
                            Id = 18,
                            Count = 0,
                            SerialNumber = "ACME-018-A1XG"
                        },
                        new
                        {
                            Id = 19,
                            Count = 0,
                            SerialNumber = "ACME-019-TFFV"
                        },
                        new
                        {
                            Id = 20,
                            Count = 0,
                            SerialNumber = "ACME-020-222K"
                        },
                        new
                        {
                            Id = 21,
                            Count = 0,
                            SerialNumber = "ACME-021-1FWZ"
                        },
                        new
                        {
                            Id = 22,
                            Count = 0,
                            SerialNumber = "ACME-022-J6Y4"
                        },
                        new
                        {
                            Id = 23,
                            Count = 0,
                            SerialNumber = "ACME-023-QE01"
                        },
                        new
                        {
                            Id = 24,
                            Count = 0,
                            SerialNumber = "ACME-024-CO2A"
                        },
                        new
                        {
                            Id = 25,
                            Count = 0,
                            SerialNumber = "ACME-025-FRMQ"
                        },
                        new
                        {
                            Id = 26,
                            Count = 0,
                            SerialNumber = "ACME-026-C0HI"
                        },
                        new
                        {
                            Id = 27,
                            Count = 0,
                            SerialNumber = "ACME-027-FXGR"
                        },
                        new
                        {
                            Id = 28,
                            Count = 0,
                            SerialNumber = "ACME-028-OAE8"
                        },
                        new
                        {
                            Id = 29,
                            Count = 0,
                            SerialNumber = "ACME-029-8ZTI"
                        },
                        new
                        {
                            Id = 30,
                            Count = 0,
                            SerialNumber = "ACME-030-NE8H"
                        },
                        new
                        {
                            Id = 31,
                            Count = 0,
                            SerialNumber = "ACME-031-XF27"
                        },
                        new
                        {
                            Id = 32,
                            Count = 0,
                            SerialNumber = "ACME-032-P7X1"
                        },
                        new
                        {
                            Id = 33,
                            Count = 0,
                            SerialNumber = "ACME-033-4XLN"
                        },
                        new
                        {
                            Id = 34,
                            Count = 0,
                            SerialNumber = "ACME-034-6GE2"
                        },
                        new
                        {
                            Id = 35,
                            Count = 0,
                            SerialNumber = "ACME-035-ZHML"
                        },
                        new
                        {
                            Id = 36,
                            Count = 0,
                            SerialNumber = "ACME-036-DEGT"
                        },
                        new
                        {
                            Id = 37,
                            Count = 0,
                            SerialNumber = "ACME-037-VIIK"
                        },
                        new
                        {
                            Id = 38,
                            Count = 0,
                            SerialNumber = "ACME-038-FI9O"
                        },
                        new
                        {
                            Id = 39,
                            Count = 0,
                            SerialNumber = "ACME-039-17FP"
                        },
                        new
                        {
                            Id = 40,
                            Count = 0,
                            SerialNumber = "ACME-040-SNYJ"
                        },
                        new
                        {
                            Id = 41,
                            Count = 0,
                            SerialNumber = "ACME-041-F84J"
                        },
                        new
                        {
                            Id = 42,
                            Count = 0,
                            SerialNumber = "ACME-042-AOST"
                        },
                        new
                        {
                            Id = 43,
                            Count = 0,
                            SerialNumber = "ACME-043-JY0A"
                        },
                        new
                        {
                            Id = 44,
                            Count = 0,
                            SerialNumber = "ACME-044-CZ3T"
                        },
                        new
                        {
                            Id = 45,
                            Count = 0,
                            SerialNumber = "ACME-045-0C63"
                        },
                        new
                        {
                            Id = 46,
                            Count = 0,
                            SerialNumber = "ACME-046-245L"
                        },
                        new
                        {
                            Id = 47,
                            Count = 0,
                            SerialNumber = "ACME-047-3OLZ"
                        },
                        new
                        {
                            Id = 48,
                            Count = 0,
                            SerialNumber = "ACME-048-MD5T"
                        },
                        new
                        {
                            Id = 49,
                            Count = 0,
                            SerialNumber = "ACME-049-DSZ4"
                        },
                        new
                        {
                            Id = 50,
                            Count = 0,
                            SerialNumber = "ACME-050-4CEA"
                        },
                        new
                        {
                            Id = 51,
                            Count = 0,
                            SerialNumber = "ACME-051-6GF9"
                        },
                        new
                        {
                            Id = 52,
                            Count = 0,
                            SerialNumber = "ACME-052-YRNA"
                        },
                        new
                        {
                            Id = 53,
                            Count = 0,
                            SerialNumber = "ACME-053-T5XY"
                        },
                        new
                        {
                            Id = 54,
                            Count = 0,
                            SerialNumber = "ACME-054-0XRH"
                        },
                        new
                        {
                            Id = 55,
                            Count = 0,
                            SerialNumber = "ACME-055-FHPF"
                        },
                        new
                        {
                            Id = 56,
                            Count = 0,
                            SerialNumber = "ACME-056-Z9HH"
                        },
                        new
                        {
                            Id = 57,
                            Count = 0,
                            SerialNumber = "ACME-057-6TUA"
                        },
                        new
                        {
                            Id = 58,
                            Count = 0,
                            SerialNumber = "ACME-058-7NA0"
                        },
                        new
                        {
                            Id = 59,
                            Count = 0,
                            SerialNumber = "ACME-059-NAVM"
                        },
                        new
                        {
                            Id = 60,
                            Count = 0,
                            SerialNumber = "ACME-060-6FYT"
                        },
                        new
                        {
                            Id = 61,
                            Count = 0,
                            SerialNumber = "ACME-061-W5FP"
                        },
                        new
                        {
                            Id = 62,
                            Count = 0,
                            SerialNumber = "ACME-062-6JBS"
                        },
                        new
                        {
                            Id = 63,
                            Count = 0,
                            SerialNumber = "ACME-063-J85Z"
                        },
                        new
                        {
                            Id = 64,
                            Count = 0,
                            SerialNumber = "ACME-064-A8UG"
                        },
                        new
                        {
                            Id = 65,
                            Count = 0,
                            SerialNumber = "ACME-065-AGVF"
                        },
                        new
                        {
                            Id = 66,
                            Count = 0,
                            SerialNumber = "ACME-066-G8LW"
                        },
                        new
                        {
                            Id = 67,
                            Count = 0,
                            SerialNumber = "ACME-067-CSWX"
                        },
                        new
                        {
                            Id = 68,
                            Count = 0,
                            SerialNumber = "ACME-068-EF0P"
                        },
                        new
                        {
                            Id = 69,
                            Count = 0,
                            SerialNumber = "ACME-069-C3YX"
                        },
                        new
                        {
                            Id = 70,
                            Count = 0,
                            SerialNumber = "ACME-070-V4FO"
                        },
                        new
                        {
                            Id = 71,
                            Count = 0,
                            SerialNumber = "ACME-071-7M1N"
                        },
                        new
                        {
                            Id = 72,
                            Count = 0,
                            SerialNumber = "ACME-072-6IRR"
                        },
                        new
                        {
                            Id = 73,
                            Count = 0,
                            SerialNumber = "ACME-073-85IQ"
                        },
                        new
                        {
                            Id = 74,
                            Count = 0,
                            SerialNumber = "ACME-074-7IGO"
                        },
                        new
                        {
                            Id = 75,
                            Count = 0,
                            SerialNumber = "ACME-075-GUS0"
                        },
                        new
                        {
                            Id = 76,
                            Count = 0,
                            SerialNumber = "ACME-076-YE3S"
                        },
                        new
                        {
                            Id = 77,
                            Count = 0,
                            SerialNumber = "ACME-077-HU26"
                        },
                        new
                        {
                            Id = 78,
                            Count = 0,
                            SerialNumber = "ACME-078-95K9"
                        },
                        new
                        {
                            Id = 79,
                            Count = 0,
                            SerialNumber = "ACME-079-51U5"
                        },
                        new
                        {
                            Id = 80,
                            Count = 0,
                            SerialNumber = "ACME-080-2R0N"
                        },
                        new
                        {
                            Id = 81,
                            Count = 0,
                            SerialNumber = "ACME-081-LPVH"
                        },
                        new
                        {
                            Id = 82,
                            Count = 0,
                            SerialNumber = "ACME-082-9371"
                        },
                        new
                        {
                            Id = 83,
                            Count = 0,
                            SerialNumber = "ACME-083-ADEH"
                        },
                        new
                        {
                            Id = 84,
                            Count = 0,
                            SerialNumber = "ACME-084-9EEO"
                        },
                        new
                        {
                            Id = 85,
                            Count = 0,
                            SerialNumber = "ACME-085-49OL"
                        },
                        new
                        {
                            Id = 86,
                            Count = 0,
                            SerialNumber = "ACME-086-ANOB"
                        },
                        new
                        {
                            Id = 87,
                            Count = 0,
                            SerialNumber = "ACME-087-DLSW"
                        },
                        new
                        {
                            Id = 88,
                            Count = 0,
                            SerialNumber = "ACME-088-11B2"
                        },
                        new
                        {
                            Id = 89,
                            Count = 0,
                            SerialNumber = "ACME-089-HTEF"
                        },
                        new
                        {
                            Id = 90,
                            Count = 0,
                            SerialNumber = "ACME-090-4BMH"
                        },
                        new
                        {
                            Id = 91,
                            Count = 0,
                            SerialNumber = "ACME-091-PX93"
                        },
                        new
                        {
                            Id = 92,
                            Count = 0,
                            SerialNumber = "ACME-092-04MA"
                        },
                        new
                        {
                            Id = 93,
                            Count = 0,
                            SerialNumber = "ACME-093-SJYM"
                        },
                        new
                        {
                            Id = 94,
                            Count = 0,
                            SerialNumber = "ACME-094-QSQM"
                        },
                        new
                        {
                            Id = 95,
                            Count = 0,
                            SerialNumber = "ACME-095-K9BV"
                        },
                        new
                        {
                            Id = 96,
                            Count = 0,
                            SerialNumber = "ACME-096-Y875"
                        },
                        new
                        {
                            Id = 97,
                            Count = 0,
                            SerialNumber = "ACME-097-08EN"
                        },
                        new
                        {
                            Id = 98,
                            Count = 0,
                            SerialNumber = "ACME-098-3719"
                        },
                        new
                        {
                            Id = 99,
                            Count = 0,
                            SerialNumber = "ACME-099-LJNZ"
                        },
                        new
                        {
                            Id = 100,
                            Count = 0,
                            SerialNumber = "ACME-100-F69H"
                        });
                });

            modelBuilder.Entity("ClassLibrary.SubmissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubmissionModels");
                });
#pragma warning restore 612, 618
        }
    }
}
