// <auto-generated />
using ClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataClassLibary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.SerialNumberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SerialNumber = "ACME-001"
                        },
                        new
                        {
                            Id = 2,
                            SerialNumber = "ACME-002"
                        },
                        new
                        {
                            Id = 3,
                            SerialNumber = "ACME-003"
                        },
                        new
                        {
                            Id = 4,
                            SerialNumber = "ACME-004"
                        },
                        new
                        {
                            Id = 5,
                            SerialNumber = "ACME-005"
                        },
                        new
                        {
                            Id = 6,
                            SerialNumber = "ACME-006"
                        },
                        new
                        {
                            Id = 7,
                            SerialNumber = "ACME-007"
                        },
                        new
                        {
                            Id = 8,
                            SerialNumber = "ACME-008"
                        },
                        new
                        {
                            Id = 9,
                            SerialNumber = "ACME-009"
                        },
                        new
                        {
                            Id = 10,
                            SerialNumber = "ACME-010"
                        },
                        new
                        {
                            Id = 11,
                            SerialNumber = "ACME-011"
                        },
                        new
                        {
                            Id = 12,
                            SerialNumber = "ACME-012"
                        },
                        new
                        {
                            Id = 13,
                            SerialNumber = "ACME-013"
                        },
                        new
                        {
                            Id = 14,
                            SerialNumber = "ACME-014"
                        },
                        new
                        {
                            Id = 15,
                            SerialNumber = "ACME-015"
                        },
                        new
                        {
                            Id = 16,
                            SerialNumber = "ACME-016"
                        },
                        new
                        {
                            Id = 17,
                            SerialNumber = "ACME-017"
                        },
                        new
                        {
                            Id = 18,
                            SerialNumber = "ACME-018"
                        },
                        new
                        {
                            Id = 19,
                            SerialNumber = "ACME-019"
                        },
                        new
                        {
                            Id = 20,
                            SerialNumber = "ACME-020"
                        },
                        new
                        {
                            Id = 21,
                            SerialNumber = "ACME-021"
                        },
                        new
                        {
                            Id = 22,
                            SerialNumber = "ACME-022"
                        },
                        new
                        {
                            Id = 23,
                            SerialNumber = "ACME-023"
                        },
                        new
                        {
                            Id = 24,
                            SerialNumber = "ACME-024"
                        },
                        new
                        {
                            Id = 25,
                            SerialNumber = "ACME-025"
                        },
                        new
                        {
                            Id = 26,
                            SerialNumber = "ACME-026"
                        },
                        new
                        {
                            Id = 27,
                            SerialNumber = "ACME-027"
                        },
                        new
                        {
                            Id = 28,
                            SerialNumber = "ACME-028"
                        },
                        new
                        {
                            Id = 29,
                            SerialNumber = "ACME-029"
                        },
                        new
                        {
                            Id = 30,
                            SerialNumber = "ACME-030"
                        },
                        new
                        {
                            Id = 31,
                            SerialNumber = "ACME-031"
                        },
                        new
                        {
                            Id = 32,
                            SerialNumber = "ACME-032"
                        },
                        new
                        {
                            Id = 33,
                            SerialNumber = "ACME-033"
                        },
                        new
                        {
                            Id = 34,
                            SerialNumber = "ACME-034"
                        },
                        new
                        {
                            Id = 35,
                            SerialNumber = "ACME-035"
                        },
                        new
                        {
                            Id = 36,
                            SerialNumber = "ACME-036"
                        },
                        new
                        {
                            Id = 37,
                            SerialNumber = "ACME-037"
                        },
                        new
                        {
                            Id = 38,
                            SerialNumber = "ACME-038"
                        },
                        new
                        {
                            Id = 39,
                            SerialNumber = "ACME-039"
                        },
                        new
                        {
                            Id = 40,
                            SerialNumber = "ACME-040"
                        },
                        new
                        {
                            Id = 41,
                            SerialNumber = "ACME-041"
                        },
                        new
                        {
                            Id = 42,
                            SerialNumber = "ACME-042"
                        },
                        new
                        {
                            Id = 43,
                            SerialNumber = "ACME-043"
                        },
                        new
                        {
                            Id = 44,
                            SerialNumber = "ACME-044"
                        },
                        new
                        {
                            Id = 45,
                            SerialNumber = "ACME-045"
                        },
                        new
                        {
                            Id = 46,
                            SerialNumber = "ACME-046"
                        },
                        new
                        {
                            Id = 47,
                            SerialNumber = "ACME-047"
                        },
                        new
                        {
                            Id = 48,
                            SerialNumber = "ACME-048"
                        },
                        new
                        {
                            Id = 49,
                            SerialNumber = "ACME-049"
                        },
                        new
                        {
                            Id = 50,
                            SerialNumber = "ACME-050"
                        },
                        new
                        {
                            Id = 51,
                            SerialNumber = "ACME-051"
                        },
                        new
                        {
                            Id = 52,
                            SerialNumber = "ACME-052"
                        },
                        new
                        {
                            Id = 53,
                            SerialNumber = "ACME-053"
                        },
                        new
                        {
                            Id = 54,
                            SerialNumber = "ACME-054"
                        },
                        new
                        {
                            Id = 55,
                            SerialNumber = "ACME-055"
                        },
                        new
                        {
                            Id = 56,
                            SerialNumber = "ACME-056"
                        },
                        new
                        {
                            Id = 57,
                            SerialNumber = "ACME-057"
                        },
                        new
                        {
                            Id = 58,
                            SerialNumber = "ACME-058"
                        },
                        new
                        {
                            Id = 59,
                            SerialNumber = "ACME-059"
                        },
                        new
                        {
                            Id = 60,
                            SerialNumber = "ACME-060"
                        },
                        new
                        {
                            Id = 61,
                            SerialNumber = "ACME-061"
                        },
                        new
                        {
                            Id = 62,
                            SerialNumber = "ACME-062"
                        },
                        new
                        {
                            Id = 63,
                            SerialNumber = "ACME-063"
                        },
                        new
                        {
                            Id = 64,
                            SerialNumber = "ACME-064"
                        },
                        new
                        {
                            Id = 65,
                            SerialNumber = "ACME-065"
                        },
                        new
                        {
                            Id = 66,
                            SerialNumber = "ACME-066"
                        },
                        new
                        {
                            Id = 67,
                            SerialNumber = "ACME-067"
                        },
                        new
                        {
                            Id = 68,
                            SerialNumber = "ACME-068"
                        },
                        new
                        {
                            Id = 69,
                            SerialNumber = "ACME-069"
                        },
                        new
                        {
                            Id = 70,
                            SerialNumber = "ACME-070"
                        },
                        new
                        {
                            Id = 71,
                            SerialNumber = "ACME-071"
                        },
                        new
                        {
                            Id = 72,
                            SerialNumber = "ACME-072"
                        },
                        new
                        {
                            Id = 73,
                            SerialNumber = "ACME-073"
                        },
                        new
                        {
                            Id = 74,
                            SerialNumber = "ACME-074"
                        },
                        new
                        {
                            Id = 75,
                            SerialNumber = "ACME-075"
                        },
                        new
                        {
                            Id = 76,
                            SerialNumber = "ACME-076"
                        },
                        new
                        {
                            Id = 77,
                            SerialNumber = "ACME-077"
                        },
                        new
                        {
                            Id = 78,
                            SerialNumber = "ACME-078"
                        },
                        new
                        {
                            Id = 79,
                            SerialNumber = "ACME-079"
                        },
                        new
                        {
                            Id = 80,
                            SerialNumber = "ACME-080"
                        },
                        new
                        {
                            Id = 81,
                            SerialNumber = "ACME-081"
                        },
                        new
                        {
                            Id = 82,
                            SerialNumber = "ACME-082"
                        },
                        new
                        {
                            Id = 83,
                            SerialNumber = "ACME-083"
                        },
                        new
                        {
                            Id = 84,
                            SerialNumber = "ACME-084"
                        },
                        new
                        {
                            Id = 85,
                            SerialNumber = "ACME-085"
                        },
                        new
                        {
                            Id = 86,
                            SerialNumber = "ACME-086"
                        },
                        new
                        {
                            Id = 87,
                            SerialNumber = "ACME-087"
                        },
                        new
                        {
                            Id = 88,
                            SerialNumber = "ACME-088"
                        },
                        new
                        {
                            Id = 89,
                            SerialNumber = "ACME-089"
                        },
                        new
                        {
                            Id = 90,
                            SerialNumber = "ACME-090"
                        },
                        new
                        {
                            Id = 91,
                            SerialNumber = "ACME-091"
                        },
                        new
                        {
                            Id = 92,
                            SerialNumber = "ACME-092"
                        },
                        new
                        {
                            Id = 93,
                            SerialNumber = "ACME-093"
                        },
                        new
                        {
                            Id = 94,
                            SerialNumber = "ACME-094"
                        },
                        new
                        {
                            Id = 95,
                            SerialNumber = "ACME-095"
                        },
                        new
                        {
                            Id = 96,
                            SerialNumber = "ACME-096"
                        },
                        new
                        {
                            Id = 97,
                            SerialNumber = "ACME-097"
                        },
                        new
                        {
                            Id = 98,
                            SerialNumber = "ACME-098"
                        },
                        new
                        {
                            Id = 99,
                            SerialNumber = "ACME-099"
                        },
                        new
                        {
                            Id = 100,
                            SerialNumber = "ACME-100"
                        });
                });

            modelBuilder.Entity("ClassLibrary.SubmissionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
